### ISSUE TITLE
Question on templates.

### ISSUE THREAD

**Issue by pandelaras** [CslaGenFork/CslaGenFork#60]
Do the new templates support the latest csla? The previous templates had support up to csla ver 4.5.7 I believe. 
Do you believe that CSLA is the framework to go behind a html 5 angular web app?

**Comment by tfreitasleal** [comment]
The templates are quite up to date - they even support the LazyGetPropery feature.

Concerning Csla 4.7 beta, the answer is yes and no:
Yes - the generated code runs on 4.7
No - there is no support for the new features.

CSLA .NET is the framework to go behind any front end. Don't forget it can be consumed as XML or JSON WebServices. If your front end can consume WebServices, you can use CSLA .NET.
