### ISSUE TITLE
HowTo - DAL/DTO and Interface Layers

### ISSUE THREAD

**Issue by chrisintampa** [CslaGenFork/CslaGenFork#97]
Hello - how can I get the codegen to generate the DTO, DAL, and Interface layers? Right now everything is being generated in the .designer file as a single class.

thanks
Chris

**Comment by tfreitasleal** [comment]
You must select a target framework with DAL

![cgf-dal-1](https://user-images.githubusercontent.com/3586655/50058806-ac001a00-0175-11e9-8491-e0c85cac7ac5.png)

And don't forget to fix the DAL namespaces 

![cgf-dal-2](https://user-images.githubusercontent.com/3586655/50058807-aefb0a80-0175-11e9-87c9-024370f58d80.png)

**Comment by chrisintampa** [comment]
Thanks! That is probably the only dropdown I didn't click into.  More questions to come.....
